name: Add bugs to bugs project

on:
  issues:
    types: [labeled]

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.4.0
        with:
          project-url: https://github.com/users/Hildirial/projects/2
          github-token: ${{ steps.install.outputs.access_token }}
          labeled: 'bug'
      - name: Install Octokit
        uses: peter-evans/install-pkg@b5c5b5f5b23d3ec5d5c5f6f00e6a1742623a3503
        with:
          package: @octokit/rest
      - name: Install dotenv
        run: npm install dotenv
      - name: Configure environment
        run: echo "PRIVATE_KEY=$(cat private-key.pem)" >> $GITHUB_ENV
      - name: Create JWT
        id: jwt
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" | base64 -d > private-key.pem
          JWT=$(./jwt.py encode --private-key private-key.pem --app-id ${{ secrets.APP_ID }})
          echo "::set-output name=jwt::${JWT}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get installation token
        id: install
        uses: octokit/request-action@v2.x
        with:
          route: POST /app/installations/:installation_id/access_tokens
          installation_id: ${{ github.event.installation.id }}
          headers: |
            authorization: Bearer ${{ steps.jwt.outputs.jwt }}
          accept: application/vnd.github.machine-man-preview+json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
