name: Add bugs to bugs project

on:
  issues:
    types: [labeled]

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Use GitHub App to create a new access token
        id: github_app_token
        uses: wei/gitHub-app-token@v1.0.4
        with:
          appId: ${{ secrets.APP_ID }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
          installationId: ${{ github.event.installation.id }}
      - name: Add issue to project
        uses: actions/add-to-project@v0.4.0
        with:
          project-url: https://github.com/users/Hildirial/projects/2
          github-token: ${{ steps.github_app_token.outputs.accessToken }}
          labeled: bug
